<?php

return [
    [
        'label' => 'Main',
        'is_label' => true,
    ],
    [
        'name' => 'Dashboard',
        'route' => 'dashboard',
        'icon' => 'home',
        'permission' => null, // No permission required
        'active_routes' => ['dashboard'],
    ],
    [
        'name' => 'Activities',
        'route' => 'activities.index',
        'icon' => 'calendar',
        'permission' => null,
        'active_routes' => ['activities.index'],
    ],
    [
        'name' => 'Enquiries',
        'route' => 'enquiries.index',
        'icon' => 'smartphone',
        'permission' => null,
        'active_routes' => ['agents.index'],
    ],
    [
        'name' => 'Services',
        'icon' => 'share-2',
        'permission' => null,
        'permission_type' => null,
        'active_routes' => ['serviceproviders.*', 'serviceitems.*'],
        'is_dropdown' => true,
        'children' => [
            [
                'name' => 'Providers',
                'route' => 'serviceproviders.index',
                'icon' => 'ti-control-record',
                'permission' => null,
                'permission_type' => 'can',
                'active_routes' => ['serviceproviders.*'],
            ],
            [
                'name' => 'Items',
                'route' => 'serviceitems.index',
                'icon' => 'ti-control-record',
                'permission' => null,
                'permission_type' => 'can',
                'active_routes' => ['serviceitems.*'],
            ],
        ],
    ],
    [
        'name' => 'Carriers',
        'route' => 'carriers.index',
        'icon' => 'rss',
        'permission' => null,
        'active_routes' => ['carriers.*'],
    ],
    [
        'name' => 'Lodges',
        'route' => 'lodges.index',
        'icon' => 'home',
        'permission' => null,
        'active_routes' => ['agents.index'],
    ],
    [
        'name' => 'Fleets',
        'icon' => 'navigation',
        'permission' => null,
        'permission_type' => null, // Use @canany directive
        'active_routes' => ['fleets.*', 'fleettypes.*', 'fleetclasses.*'],
        'is_dropdown' => true,
        'children' => [
            [
                'name' => 'Fleets',
                'route' => 'fleets.index',
                'icon' => 'ti-control-record',
                'permission' => null,
                'permission_type' => 'can',
                'active_routes' => ['fleets.index'],
            ],
            [
                'name' => 'Types',
                'route' => 'fleettypes.index',
                'icon' => 'ti-control-record',
                'permission' => null,
                'permission_type' => 'can',
                'active_routes' => ['fleettypes.*'],
            ],
            [
                'name' => 'Classes',
                'route' => 'fleetclasses.index',
                'icon' => 'ti-control-record',
                'permission' => null,
                'permission_type' => 'can',
                'active_routes' => ['fleetclasses.*'],
            ],
        ],
    ],
    [
        'name' => 'Drivers',
        'icon' => 'user',
        'permission' => null,
        'permission_type' => null,
        'active_routes' => ['drivers.*', 'drivertypes.*'],
        'is_dropdown' => true,
        'children' => [
            [
                'name' => 'Drivers',
                'route' => 'drivers.index',
                'icon' => 'ti-control-record',
                'permission' => null,
                'permission_type' => 'can',
                'active_routes' => ['drivers.index'],
            ],
            [
                'name' => 'Types',
                'route' => 'drivertypes.index',
                'icon' => 'ti-control-record',
                'permission' => null,
                'permission_type' => 'can',
                'active_routes' => ['drivertypes.*'],
            ],
        ],
    ],
    [
        'name' => 'Trips',
        'icon' => 'map-pin',
        'permission' => null,
        'permission_type' => null, // Use @canany directive
        'active_routes' => ['trips.*', 'triptypes.*'],
        'is_dropdown' => true,
        'children' => [
            [
                'name' => 'Trips',
                'route' => 'trips.index',
                'icon' => 'ti-control-record',
                'permission' => 'user::manage',
                'permission_type' => 'can',
                'active_routes' => ['trips.*'],
            ],
            [
                'name' => 'Types',
                'route' => 'triptypes.index',
                'icon' => 'ti-control-record',
                'permission' => 'role::manage',
                'permission_type' => 'can',
                'active_routes' => ['triptypes.*'],
            ],
        ],
    ],
    [
        'name' => 'Bookings',
        'route' => 'bookings.index',
        'icon' => 'download',
        'permission' => null,
        'active_routes' => ['bookings.*'],
    ],
    [
        'name' => 'Reservations',
        'route' => 'agents.index',
        'icon' => 'database',
        'permission' => null,
        'active_routes' => ['agents.index'],
    ],
    [
        'name' => 'Vehicles',
        'route' => 'agents.index',
        'icon' => 'truck',
        'permission' => null,
        'active_routes' => ['agents.index'],
    ],
    [
        'name' => 'Agent',
        'route' => 'agents.index',
        'icon' => 'user',
        'permission' => null,
        'active_routes' => ['agents.index'],
    ],
    [
        'name' => 'Channels',
        'route' => 'channels.index',
        'icon' => 'airplay',
        'permission' => null,
        'active_routes' => ['channels.*'],
    ],
    [
        'name' => 'Currencies',
        'route' => 'currencies.index',
        'icon' => 'dollar-sign',
        'permission' => null,
        'active_routes' => ['currencies.*'],
    ],
    [
        'name' => 'User management',
        'icon' => 'users',
        'permission' => ['view::user', 'view::role', 'view::permission', 'view::module'],
        'permission_type' => 'canany',
        'active_routes' => ['users.*', 'roles.*', 'permissions.*', 'system-modules.*'],
        'is_dropdown' => true,
        'children' => [
            [
                'name' => 'Users',
                'route' => 'users.index',
                'icon' => 'ti-control-record',
                'permission' => 'user::manage',
                'permission_type' => 'can',
                'active_routes' => ['users.*'],
            ],
            [
                'name' => 'Roles',
                'route' => 'roles.index',
                'icon' => 'ti-control-record',
                'permission' => 'role::manage',
                'permission_type' => 'can',
                'active_routes' => ['roles.*'],
            ],
            [
                'name' => 'Permissions',
                'route' => 'permissions.index',
                'icon' => 'ti-control-record',
                'permission' => 'permission::manage',
                'permission_type' => 'can',
                'active_routes' => ['permissions.index', 'permissions.store', 'permissions.update', 'permissions.destroy'],
            ],
            [
                'name' => 'System Modules',
                'route' => 'system-modules.index',
                'icon' => 'ti-control-record',
                'permission' => 'view::module',
                'permission_type' => 'can',
                'active_routes' => ['system-modules.index', 'system-modules.store', 'system-modules.update', 'system-modules.destroy'],
            ],
        ],
    ],
];
